### ISSUE TITLE
Issue with SVG files from version v17.1.3

### ISSUE THREAD

**Issue by ShamaGarg** [capricorn86/happy-dom#1750]
While updating happy-dom to v17.1.8, we have started getting this error in our react application:
```
Failed to execute 'createAttributeNS' on 'Document': The namespace URI provided ('') is not valid for the qualified name provided ('xmlns:xlink').

NamespaceError: Failed to execute 'createAttributeNS' on 'Document': The namespace URI provided ('') is not valid for the qualified name provided ('xmlns:xlink').

at HTMLDocument.createAttributeNS (\node_modules\happy-dom\src\nodes\document\Document.ts:1258:10)
at SVGSVGElement.setAttribute (\node_modules\happy-dom\src\nodes\element\Element.ts:702:42)
```

It looks like that the error is caused by SVG files having notations with 
```
xmlns="http://www.w3.org/2000/svg" 
xmlns:xlink="http://www.w3.org/1999/xlink"
```

We are currently on v17.1.1 and upgrading it to v17.1.8. But it looks like it is mostly because of the change in v17.1.3

**Comment by mdupont** [comment]
I have the same issue with happy-dom v17.1.8 when parsing SVGs. The second attribute `xmlns:xlink`is treated as if it does not have a namespace URI, which triggers the error in Document.

The following minimal Node script can reproduce the issue:

```js
const { Window } = require('happy-dom');

const window = new Window();
const document = window.document;

document.body.innerHTML = "<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'></svg>";
console.log(document.body.innerHTML);

window.happyDOM.close();
```

**Comment by ShamaGarg** [comment]
Hi David (@capricorn86),

Are there any updates on this please?

**Comment by ShamaGarg** [comment]
> Hi David ([@capricorn86](https://github.com/capricorn86)),
> 
> Are there any updates on this please?

Hi David (@capricorn86),

Do you have any resolutions/suggestions for this one, please? It's stopping us to upgrade to newer versions.

Thanks!

**Comment by capricorn86** [comment]
Thank you for reporting @ShamaGarg and @mdupont! 🙂 

The issue has been fixed in v17.3.1.

**Comment by EvHaus** [comment]
@capricorn86 This is still happening for me in 17.4.0. To reproduce use this code:

```
import { Window } from 'happy-dom';

const window = new Window({ url: 'https://localhost:8080' });
const document = window.document;

document.body.innerHTML =
  '<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><path d="M9.057 8l-2.862 2.862a.667.667 0 00.943.943l3.333-3.334a.667.667 0 000-.942L7.138 4.195a.667.667 0 10-.943.943L9.057 8z" id="a"/></defs><g fill="none" fill-rule="evenodd"><mask id="b" fill="#fff"><use xlink:href="#a"/></mask><use fill="#000" fill-rule="nonzero" xlink:href="#a"/><g mask="url(#b)" fill="#333"><path d="M0 0h16v16H0z"/></g></g></svg>';

console.log(document.body.innerHTML);
```

Here it is in Stackblitz: https://stackblitz.com/edit/stackblitz-starters-nkygzk2h?file=index.js

**Comment by capricorn86** [comment]
@EvHaus It seems like handling the "xlink" namespace and unknown prefixes where missing. It should be fixed now in [v17.4.1](https://github.com/capricorn86/happy-dom/releases/tag/v17.4.1).

There is also ongoing work to make DOM parsing more spec compliant in general in https://github.com/capricorn86/happy-dom/pull/1666

**Comment by ShamaGarg** [comment]
Unfortunately, it is still same issue in v17.4.1

**Comment by capricorn86** [comment]
@ShamaGarg The first issue that was fixed was that an error was thrown during parsing of HTML, but it seems like your error was related to it being thrown in `Element.setAttribute()`, which also has been fixed now.

Hopefully all issues related to this has been solved now 🤞

**Comment by EvHaus** [comment]
THanks for the quick fixes @capricorn86. The errors are resolved for me in 17.4.1. 🎉

**Comment by ShamaGarg** [comment]
Thanks @capricorn86 , 17.4.2 fixes the issue 👍
