### ISSUE TITLE
DOMRect is not defined

### ISSUE THREAD

**Issue by valtism** [capricorn86/happy-dom#486]
Hi. Completely new to this library and testing, but in my `vitest` and `happy-dom` setup I run into this issue with a component that is defining initial state using the DOMRect constructor (`new DOMRect()`).

I am guessing that this is because it is not implemented in this library. Same goes for `jsdom`.

**Comment by capricorn86** [comment]
Thanks for reporting @valtism! :slightly_smiling_face: 

DOMRect did exist, but was only used internally. It was not exported in Window. I have fixed that now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v4.1.0

**Comment by valtism** [comment]
@capricorn86 Thanks for getting onto this so quickly.

I am still having issues with `new DOMRect()` not being defined, even after updating the library, when I unstub it.

<img width="646" alt="ReferenceError: DOMRect is not defined" src="https://user-images.githubusercontent.com/1286001/170608577-cb1707c0-457d-4047-a128-319d49874e3a.png">

Am I doing something wrong here?

**Comment by jackfranklin** [comment]
@capricorn86 I am seeing the same issues as @valtism, is there anything I can do to help debug?
