### ISSUE TITLE
Element.matches fails when using non-matching descendant selector on element attached to document

### ISSUE THREAD

**Issue by IGx89** [capricorn86/happy-dom#622]
```ts
const element = document.createElement('div');
document.appendChild(element);
expect(element.matches('.nonexistent-class div')).toBe(false);
```

```
TypeError: Cannot read properties of undefined (reading 'split')

  296 |     ): { priorityWeight: number; matches: boolean } {
  297 |             const regexp = new RegExp(CLASS_REGEXP, 'g');
> 298 |             const classList = element.className.split(' ');
	  |                                                 ^
  299 |             const classSelector = selector.split(':')[0];
  300 |             let priorityWeight = 0;
  301 |             let match: RegExpMatchArray;

  at SelectorItem.matchesClass (src/query-selector/SelectorItem.ts:298:39)
  at SelectorItem.match (src/query-selector/SelectorItem.ts:91:24)
  at Function.matchesSelector (src/query-selector/QuerySelector.ts:107:27)
  at Function.matchesSelector (src/query-selector/QuerySelector.ts:113:15)
  at Function.matchesSelector (src/query-selector/QuerySelector.ts:113:15)
  at Function.matchesSelector (src/query-selector/QuerySelector.ts:113:15)
  at Function.match (src/query-selector/QuerySelector.ts:66:24)
  at HTMLElement.matches (src/nodes/element/Element.ts:734:24)
```

**Comment by capricorn86** [comment]
Thanks @IGx89 for your contribution! :slightly_smiling_face: 

Your fix has been released.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.5.13

**Comment by cristianstu** [comment]
I was having this issue, I'm still getting a similar error with version 7.5.3 but now it is:
> TypeError: Cannot read properties of null (reading 'className')

**Comment by capricorn86** [comment]
It seems like the problem isn't completely fixed. Re-opening.

**Comment by IGx89** [comment]
@cristianstu Can you share your selectors and HTML with us?

**Comment by cristianstu** [comment]
Sure, I'm actually using testing library, not happy dom directly, this is the stack trace:

```
 ❯ test/pages/login.test.tsx:86:26
     84|     renderLogin();
     85| 
     86|     const button = screen.getByRole('button');
       |                          ^
     87|     const username = screen.getByLabelText<HTMLInputElement>('Username…
     88|     const password = screen.getByLabelText<HTMLInputElement>('Password…



⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[14/16]⎯

 FAIL  test/app.test.tsx > App > navigate when click on an item menu
TypeError: Cannot read properties of null (reading 'className')
 ❯ SelectorItem.matchesClass node_modules/happy-dom/lib/query-selector/SelectorItem.js:249:35
 ❯ SelectorItem.match node_modules/happy-dom/lib/query-selector/SelectorItem.js:72:33
 ❯ Function.matchesSelector node_modules/happy-dom/lib/query-selector/QuerySelector.js:87:33
 ❯ Function.matchesSelector node_modules/happy-dom/lib/query-selector/QuerySelector.js:91:21
 ❯ Function.match node_modules/happy-dom/lib/query-selector/QuerySelector.js:59:33
 ❯ CSSStyleDeclarationElementStyle.parseCSSRules node_modules/happy-dom/lib/css/declaration/utilities/CSSStyleDeclarationElementStyle.js:230:73
```

**Comment by IGx89** [comment]
Thanks! That's actually not Element.matches so this is a separate issue. Looks like something in your CSS style sheet is triggering the exception.

**Comment by IGx89** [comment]
@cristianstu I looked over the code and found a (different) way to reproduce that specific error. I've submitted #625 to fix it -- hopefully it'll fix your issue!

**Comment by cristianstu** [comment]
> @cristianstu I looked over the code and found a (different) way to reproduce that specific error. I've submitted #625 to fix it -- hopefully it'll fix your issue!

Perfect, Thank you!

**Comment by capricorn86** [comment]
Closing this issue as #625 was created for the other bug.

**Comment by IGx89** [comment]
@cristianstu give v7.5.14 a try and let us know!

**Comment by capricorn86** [comment]
Thanks for your contribution @IGx89! 🙂 

Your fix is in now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.5.14

**Comment by cristianstu** [comment]
> @cristianstu give v7.5.14 a try and let us know!

It's fixed! Everything looks nice, thanks!
